name: Electron main builds
on: 
  push:
    branches:
     - main
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  npm-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          submodules: true
      - name: Setup Node JS
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 15.x

      - name: Install
        run: npm install

      - name: Test
        run: npm run test
        env:
          ELECTRON_TEST: true

  Release-Linux:
    runs-on: ubuntu-latest
    needs: npm-test
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          submodules: true
      - name: Setup Node JS
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 15.x

      - name: Update
        run: npm update

      - name: Install
        run: npm install

      - name: Build Packs
        run: npm run pack

      - name: Get The Bds Maneger Version
        run: |
          sudo apt install -y jq
          echo "BDS_VER=\"$(cat package.json| jq -r .version)\"" >> dist/release_config.txt
          echo "ELECTRON_VER=$(cat package.json| jq -r .devDependencies.electron)" >> dist/release_config.txt
          echo "BDS_CORE_VER=$(cat package.json| jq -r '.dependencies["@the-bds-maneger/core"]')" >> dist/release_config.txt
          echo "COMMIT_ME=\"$(git show -s --format=%s -1)\"" >> dist/release_config.txt

      - uses: actions/upload-artifact@main
        with:
          name: linux
          retention-days: 1
          path: dist/*.*

  Release-Macos:
    runs-on: macos-latest
    needs: npm-test
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          submodules: true
      - name: Setup Node JS
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 15.x

      - name: Update
        run: npm update

      - name: Install
        run: npm install

      - name: Build Packs
        run: npm run pack

      - uses: actions/upload-artifact@main
        with:
          name: macos
          retention-days: 1
          path: dist/*.*

  Release-Windows:
    runs-on: windows-latest
    needs: npm-test
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          submodules: true
      - name: Setup Node JS
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 15.x

      - name: Update
        run: npm update

      - name: Install
        run: npm install

      - name: Build Packs
        continue-on-error: true
        run: npm run pack

      - uses: actions/upload-artifact@main
        with:
          name: windows
          retention-days: 1
          path: dist/*.*

  Release:
    runs-on: ubuntu-latest
    needs: [npm-test, Release-Windows, Release-Linux, Release-Macos]
    steps:
      - uses: actions/download-artifact@v2

      - name: Getting the env in the file
        run: |
          cat */*release_config.txt >> $GITHUB_ENV
          cat */*release_config.txt

      - run: rm -fv $(find -L -maxdepth 1 -type f -name '*.y*ml' | sed 's|./||g' | sed 's|\.||g') */*release_config.txt

      - name: Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Bds Maneger Version ${{ env.BDS_VER }}
          tag_name: ${{ github.run_id }}
          files: '*/*'
          prerelease: true
          body: |
            The Bds Maneger With Electron: ${{ env.ELECTRON_VER }},
            Bds Maneger Core version: ${{ env.BDS_CORE_VER }}
            ${{ env.COMMIT_ME }}
