name: Pull Request electron Test
on: [pull_request]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          submodules: true
      - name: Setup Node JS
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 15.x

      - name: Update
        run: npm update

      - name: Install
        run: npm install

      - name: Test
        run: npm run test